'use client'

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'

type Listing = { id: number; title: string; description: string; tags: string[]; health: { score: number; breakdown: Record<string, number>; issues: string[] } }

export default function ListingWorkspace({ listingId }: { listingId: string }) {
  const [listing, setListing] = useState<Listing | null>(null); const [suggestion, setSuggestion] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState<string | null>(null)
  useEffect(() => { fetch(`/api/etsy/listings/${listingId}`).then((res) => res.json()).then((data) => setListing(data.listing ?? null)) }, [listingId])
  const optimize = async () => { if (!listing) return; setLoading(true); setError(null); const res = await fetch('/api/optimize-listing', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ current_title: listing.title, current_description: listing.description, current_tags: listing.tags.join(', '), platform: 'etsy', listing_id: listing.id }) }); const data = await res.json(); if (res.ok) setSuggestion(data); else setError(data.error ?? 'Could not generate suggestions.'); setLoading(false) }
  const saveReview = async () => { if (!listing || !suggestion) return; setLoading(true); setSaved(null); const res = await fetch(`/api/etsy/listings/${listing.id}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: suggestion.title, description: suggestion.description, tags: suggestion.tags }) }); const data = await res.json(); if (res.ok) { setListing({ ...listing, ...data.listing }); setSaved('Reviewed changes saved locally. They have not been published to Etsy.'); } else setError(data.error ?? 'Could not save changes.'); setLoading(false) }
  if (!listing) return <div className="mx-auto max-w-6xl p-8 text-muted-foreground">Loading listing…</div>
  return <div className="mx-auto max-w-7xl px-5 py-12"><p className="eyebrow">Listing Workspace</p><h1 className="mt-2 font-display text-4xl">Review changes before publishing</h1><p className="mt-3 text-muted-foreground">Craftly Listing Health: {listing.health.score}/100 — not an official Etsy score.</p><div className="mt-8 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Current Etsy listing</h2><h3 className="mt-5 text-sm font-medium text-muted-foreground">TITLE</h3><p className="mt-1">{listing.title}</p><h3 className="mt-5 text-sm font-medium text-muted-foreground">DESCRIPTION</h3><p className="mt-1 whitespace-pre-wrap text-sm">{listing.description}</p><h3 className="mt-5 text-sm font-medium text-muted-foreground">TAGS</h3><p className="mt-1 text-sm">{listing.tags.join(', ') || 'No tags imported'}</p></section><section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">AI suggestions</h2><Button className="mt-5" onClick={optimize} disabled={loading}>{loading ? 'Generating…' : 'Generate suggestions'}</Button>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}{saved && <p className="mt-4 text-sm text-emerald-400">{saved}</p>}{suggestion && <div className="mt-5 space-y-5"><div><h3 className="text-sm text-muted-foreground">SUGGESTED TITLE</h3><Textarea value={suggestion.title} onChange={(event) => setSuggestion({ ...suggestion, title: event.target.value })} /></div><div><h3 className="text-sm text-muted-foreground">SUGGESTED DESCRIPTION</h3><Textarea className="min-h-44" value={suggestion.description} onChange={(event) => setSuggestion({ ...suggestion, description: event.target.value })} /></div><div><h3 className="text-sm text-muted-foreground">SUGGESTED TAGS</h3><p className="mt-1 text-sm">{suggestion.tags?.join(', ')}</p></div><Button onClick={saveReview} disabled={loading}>Accept and save reviewed changes</Button><p className="text-xs text-muted-foreground">Saving updates your Craftly workspace only. Publishing to Etsy remains a separate, confirmed action.</p></div>}</section><section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Listing Health</h2>{Object.entries(listing.health.breakdown).map(([label, score]) => <div className="mt-4" key={label}><div className="flex justify-between text-sm"><span className="capitalize">{label}</span><span>{score}/20</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Number(score) * 5}%` }} /></div></div>)}<h3 className="mt-7 font-medium">Top improvements</h3><ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-muted-foreground">{listing.health.issues.map((issue) => <li key={issue}>{issue}</li>)}</ol></section></div></div>
}
