export const PLATFORMS = [
  { label: 'Etsy Listing (1:1)', size: '1024x1024' },
  { label: 'Instagram Post (1:1)', size: '1024x1024' },
  { label: 'Pinterest Pin (2:3)', size: '1024x1536' },
  { label: 'TikTok / Reels Cover (9:16)', size: '1024x1536' },
  { label: 'YouTube Thumbnail (16:9)', size: '1536x1024' },
  { label: 'Facebook Ad (4:5)', size: '1024x1536' },
]

export const STYLES = [
  'Studio product photography',
  'Lifestyle scene',
  'Minimalist',
  'Vintage',
  'Bold & colorful',
]

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Japanese',
  'Korean',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Russian',
  'Arabic',
  'Turkish',
  'Polish',
  'Vietnamese',
  'Thai',
  'No text',
]

export const VARIANT_COUNTS = [2, 3, 4]

export const CATEGORIES = [
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'accessories', label: 'Bags & Accessories' },
  { value: 'shoes', label: 'Shoes' },
  { value: 'home_decor', label: 'Home & Living Decor' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'art_prints', label: 'Art Prints & Wall Decor' },
  { value: 'digital', label: 'Digital Products & Printables' },
  { value: 'craft_supplies', label: 'Craft Supplies & Tools' },
  { value: 'paper_party', label: 'Paper & Party Supplies' },
  { value: 'wedding', label: 'Weddings' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'baby', label: 'Baby & Kids' },
  { value: 'pet', label: 'Pet Supplies' },
  { value: 'beauty', label: 'Beauty & Bath' },
  { value: 'food', label: 'Food & Drink' },
  { value: 'vintage', label: 'Vintage & Antiques' },
  { value: 'handmade_crafts', label: 'Handmade Crafts & Sculpture' },
  { value: 'collectibles', label: 'Collectibles & Figurines' },
  { value: 'candles_fragrance', label: 'Candles & Fragrance' },
  { value: 'stationery', label: 'Stationery & Office' },
  { value: 'plants_garden', label: 'Plants & Garden' },
  { value: 'electronics', label: 'Electronics & Accessories' },
  { value: 'sports_outdoors', label: 'Sports & Outdoors' },
  { value: 'musical_instruments', label: 'Musical Instruments' },
  { value: 'books_media', label: 'Books, Movies & Music' },
  { value: 'photography', label: 'Photography Gear' },
  { value: 'generic', label: 'Other / General' },
]
